FROM node:20-alpine

WORKDIR /app

# 1. Копируем только файлы зависимостей (это самый важный слой!)
COPY . .

# 2. Устанавливаем зависимости (кэшируется если не менялись package*.json)
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "--port", "5173"]