services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.dev.react
        container_name: react-app
        ports:
            - "3000:5173" # Локально:3000 → в контейнере:5173
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - ./package-lock.json:/app/package-lock.json
        environment:
            - CHOKIDAR_USEPOLLING=true # Для отслеживания изменений файлов в Docker
